name: First Pipeline
on: 
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello CI/CD"

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Compile
        run: javac -d out src/main/java/App.java
      
      - name: Run
        run: java -cp out App
    



